name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        Example: When importing a ForeFlight CSV with simulator aircraft, the aircraft don't appear in the dropdown.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to Aircraft Management
        2. Click "Import from ForeFlight CSV"
        3. Upload CSV file with simulator entries
        4. Notice simulators are missing from dropdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        Example: All aircraft from the CSV, including simulators, should appear in the dropdown.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Example: Only physical aircraft appear; simulator entries are missing.
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running Flight Budget Calculator?
      options:
        - Browser (opened index.html directly)
        - Docker (local deployment)
        - Docker (Portainer)
        - Docker (other container platform)
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Version
      description: What browser are you using?
      placeholder: "Example: Chrome 120.0.6099.129"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "Example: macOS 14.1, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Application Version
      description: What version of Flight Budget Calculator? (Check footer or Docker tag)
      placeholder: "Example: v1.2.3, latest, develop"

  - type: textarea
    id: console-errors
    attributes:
      label: Browser Console Errors
      description: Open browser DevTools (F12) and paste any errors from the Console tab
      placeholder: |
        Example:
        Uncaught TypeError: Cannot read property 'equipType' of undefined
            at parseCSV (app.js:123)
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: csv-sample
    attributes:
      label: Sample Data (if CSV-related)
      description: If the issue involves CSV import, provide a few sample rows (remove personal data)
      placeholder: |
        Date,Aircraft ID,Aircraft Type,Route,...
        2024-01-15,N12345,Cessna 172,KBOS-KBOS,...
      render: csv

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application unusable
        - High - Major feature broken
        - Medium - Feature partially broken
        - Low - Minor annoyance
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any workaround for this issue?
      placeholder: |
        Example: Manually adding aircraft works, but CSV import doesn't.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: This started happening after upgrading to the latest version.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### What happens next?

        1. Your bug report will be reviewed and triaged
        2. We may ask for additional information
        3. Once confirmed, it will be prioritized for fixing
        4. You'll be notified when a fix is released

        **Want to help fix it?** Check our [Contributing Guide](https://github.com/ryakel/flight-budget/wiki/Contributing) to submit a pull request!
